### ISSUE TITLE
Process state says "RUNNING" even if service has crashed

### ISSUE THREAD

**Issue by wearhere** [mixmaxhq/custody#2]
This is because the processes we run are typically build (`gulp`) processes, that launch and monitor child webserver processes (using `gulp-nodemon`). When the webserver crashes, `gulp` remains healthy, and developers are none the wiser.

Implementation ideas are discussed [here](https://github.com/mixmaxhq/custody/wiki/Enhanced-statuses).

**Comment by wearhere** [comment]
@gaastonsr if you
1. check out https://github.com/mixmaxhq/custody/tree/enhanced_statuses and https://github.com/mixmaxhq/contacts/tree/enhanced_process_status,
2. restart contacts,
3. and start custody
you'll see a special message flash in the `state` column 😉

**Comment by gaastonsr** [comment]
```html
<blink>hello gaston</blink>
```
🙂

**Comment by wearhere** [comment]
Moved implementation ideas to https://github.com/mixmaxhq/custody/wiki/Enhanced-statuses and added some more ideas
