### ISSUE TITLE
Let logs grow beyond initial scrollback

### ISSUE THREAD

**Issue by wearhere** [mixmaxhq/custody#49]
We initially load 100 lines of logs to [make the log load snappily](https://github.com/mixmaxhq/custody/blob/3ad9a4e8a7a0f3c65c28ebea39c742c924c1eb58/src/components/processDetails/ProcessLog.jsx#L10).

We then also use this number as the value of the [`scrollback` parameter](https://github.com/mixmaxhq/custody/blob/3ad9a4e8a7a0f3c65c28ebea39c742c924c1eb58/src/components/processDetails/ProcessLog.jsx#L98) on the log component. This means that the component will only ever show 100 lines of logs.

But @evanhellmuth points out that it would be nice to let the logs grow beyond that so if you're working on a service for a prolonged period of time you can see historical errors. I think we might be able to try this without performance concerns. Maybe we shouldn't let it grow indefinitely per the concerns about memory in #48, but maybe like 1000 lines would be fine.

**Comment by evanhellmuth** [comment]
🙏
