### ISSUE TITLE
Add maintail output

### ISSUE THREAD

**Issue by wearhere** [mixmaxhq/custody#57]
@logandavis says
> if something errors i can see what service it was in, not have to guess which one and tail that in custody
> also i can console.log anywhere in the backend and it just shows up, without ducking into a specific service

**Comment by logandavis** [comment]
Perhaps we could start custody with a specific flag, e.g. `custody-cli -m` for maintail? Or `-f` for foreground? 

Alternately we could add a dummy entry to the list of running services called "maintail" and allow users to select it to see the maintail?
